m_textbox_text = "1";
m_textbox_label = "units"
m_textbox_fa = fa_right;
m_textbox_sizeRestriction = 10;
m_textbox_state = 3; //0 - unchanged, 1 - valid, 2 - invalid, 3, 4, 5 - optional equivalents
m_textbox_validate_flag = input_mask.units;
m_textbox_width = 170;
m_tab_order = 14;
m_textbox_default = "1";